language: cpp

sudo: false

os:
  - osx

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc
      - g++
      - cmake
      - qt5-default
      - qtbase5-dev-tools
      - qt5-qmake

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; brew install qt5; fi

cache: ccache

script:
  - ./travis.sh

before_deploy:
  - make -C build package

deploy:
  provider: releases
  api_key: "gQz+KbddwbnLgXsOiz7RCxRrQpRyWlXYHwrwC+hu62hFxfGMvN8Keg8bjdzLPKa03fS/zyaeGTCk8+fpVdyacA0NM0pyG/TAceogvaA8Tc92WbqYF0C/cgp2iHGjqG9XZ6dDH70eaHdCB75DBjJ4oHg0v4BG2V0+owk9prmn1Zk="
  file: "build/acrostica-*-Darwin*"
  skip_cleanup: true
