language: cpp

sudo: false

os:
  - osx

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc
      - g++
      - cmake
      - qt5-default
      - qtbase5-dev-tools
      - qt5-qmake

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; brew install qt5; fi

cache: ccache

script:
  - "./travis.sh"

before_deploy:
  - make -C build package

deploy:
  provider: releases
  api_key:
    secure: SSwEeuT6tjCSPGPmbJxmtBHDWOsNhXzj4t0/3kyqRSWmtEHbRcDh/VVPpyore1JxPY7Kc/OD94JdwojMAZgrMeJfVWjWvBxwo5yzFGpFT3Qi8MEop5/WndyIfIOxK4ccDC+0t9Y8ujKGaL7njatewDDTU98ReXzVzFcrglbeD78=
  file: build/acrostica-*-Darwin*
  on:
    repo: jamessan/acrostica
    tags: true
