language: cpp

sudo: false

os:
  - osx
  - linux

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
      - gcc
      - g++
      - cmake
      - qt5-default
      - qtbase5-dev-tools
      - qt5-qmake

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install qt ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

cache: ccache

script:
  - "./travis.sh"

before_deploy:
  - if [ "$TRAVIS_OS_NAME" != osx ]; then make -C build package; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then mv build/bin/acrostica.dmg build/bin/acrostica-"${TRAVIS_TAG}".dmg; fi

deploy:
  provider: releases
  api_key:
    secure: "BtJirBSoIIyxy2PPpXfnj+RWLCmij28J8aMkj38OUTu1BfO+ayZ6Dex62HcJLKl1xdwTs3lzZrq2QmnrQwmUXGtTx0LTNfNOOeAKNfx7C2qHF5JmcjzYBZOppMwNqOXGFg3t5zNqs5Dpa/gQkKbu18ALOIL1Q2vtB24iR611Yfc="
  file:
    - build/bin/acrostica-${TRAVIS_TAG}.dmg
  skip_cleanup: true
  on:
    repo: jamessan/acrostica
    tags: true
