language: cpp

sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - cmake
      - qtbase5-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; brew install qt5; fi

script:
  - mkdir build && cd build && cmake ..
  - make -C build
