language: cpp

sudo: false

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - cmake
      - qt5-default
      - qtbase5-dev-tools
      - qt5-qmake

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; brew install qt5; fi

cache: ccache

script:
  - mkdir build && (cd build && cmake ..)
  - make -C build
